### ISSUE TITLE
荣耀不应该识别成华为

### ISSUE THREAD

**Issue by chDios** [heeroluo/just4#1]
{ name: 'huawei', regExp: /\b(?:huawei|honor)/i },

**Comment by heeroluo** [comment]
可以具体描述一下哪些场景需要区分荣耀和华为吗？

**Comment by chDios** [comment]
> 可以具体描述一下哪些场景需要区分荣耀和华为吗？

实际不就是两个不同的品牌嘛，获取相关品牌信息跳转至各自的应用商店，荣耀判断成华为这时候不就不合理了嘛

**Comment by heeroluo** [comment]
好的，后续版本会考虑把两者分开。

**Comment by heeroluo** [comment]
> { name: 'huawei', regExp: /\b(?:huawei|honor)/i },

其实有好些手机浏览器的 User-Agent  中并不会包含品牌关键字。我手上的荣耀 30 就是这样，只有型号（BMH-AN10）：

> Mozilla/5.0 (Linux; Android 12; HarmonyOS; BMH-AN10; HMSCore 6.14.0.302) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.196 HuaweiBrowser/15.0.7.301 Mobile Safari/537.36

所以我在识别品牌的时候，还会通过型号规则去匹配。而荣耀的手机型号跟华为的手机型号，似乎是一样的规则，很难区分开。

如果你知道他们型号规则上的区别，可以告诉我；否则基于型号匹配上的考虑，我暂时不会把他们区分开来了。
